import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Mike Villarreal</title>
        <meta name="description" content="Generated by..." />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1>This is my canvas, im gonna begin sharing stuff soon...</h1>
      </main>
    </div>
  );
}
